### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by opensourcegeek** [actix/actix-remote#1]
Is this something you're still exploring by any chance?

**Comment by fafhrd91** [comment]
i am not planing to continue this project, if anyone wants i can give permission for this repo

**Comment by opensourcegeek** [comment]
I really like the idea of being able to run actors in separate boxes and have some coordination between them. Is there a reason for not continuing with it, i.e do you not see a lot of potential in this direction?

**Comment by fafhrd91** [comment]
I think it is better to use specialized message broker. building new one is not trivial task
